project:
  type: website
  resources:
    - CNAME
  output-dir: docs
  
website:
  title: "Manh ND"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/manhnguy
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true

comments:
    repo: manhnguy/Manhnd

